// weapons.js — weapon catalog: combat stats, blade visuals.
// Rarity is fixed per weapon (what it looks like, where it drops). Depth beyond that is a
// pure collection stat: stars (from finding duplicates) and level (bought with coins), tracked
// per-weapon in progress.js and applied via progress.gearMultOf('weapon', id).
export const WEAPONS = [
  { id:'blade', name:'Spore Blade', icon:'🗡️', rarity:0, type:'sword',
    dmg:0, atkSpeed:1.0, range:0, crit:0, knockback:1.0, special:null,
    finisher:{type:'burst', name:'Spore Burst', radius:3.5, mult:0.6},
    color:0xbfefff, emissive:0x3fa8cc, geomScale:{x:1,y:1,z:1},
    desc:"The hunter's trusted starting blade. Balanced in every way." },
  { id:'dagger', name:'Bone Dagger', icon:'🔪', rarity:0, type:'dagger',
    dmg:-3, atkSpeed:0.72, range:-0.3, crit:0.14, knockback:0.6, special:null,
    finisher:{type:'chainhit', name:'Backstab Frenzy'},
    color:0xe8e4d0, emissive:0x8a8470, geomScale:{x:0.7,y:0.55,z:0.85},
    desc:'Featherlight. Strikes fast and often — built for critical openings.' },
  { id:'cleaver', name:'Verdant Cleaver', icon:'🪓', rarity:1, type:'axe',
    dmg:5, atkSpeed:1.18, range:0.2, crit:0, knockback:1.1, special:{type:'cleave', arc:0.28},
    finisher:{type:'sweep', name:'Bloom Reaper', arcBonus:0.4, knockMult:2.5},
    color:0x7ec850, emissive:0x2a5a12, geomScale:{x:2.1,y:0.7,z:1.5},
    desc:'A wide, heavy blade that sweeps through packed Blooms.' },
  { id:'thornfang', name:'Thornfang', icon:'🔱', rarity:2, type:'spear',
    dmg:7, atkSpeed:0.95, range:0.9, crit:0, knockback:0.9, special:{type:'execute', threshold:0.25, bonus:0.6},
    finisher:{type:'pierce', name:'Impaling Thrust', extraRange:2.2},
    color:0xff5a4a, emissive:0x8a1a1a, geomScale:{x:0.5,y:1.75,z:0.5},
    desc:'Long-reaching thorn-forged spear. Finishes wounded prey instantly.' },
  { id:'rapier', name:'Ember Rapier', icon:'🤺', rarity:2, type:'sword',
    dmg:8, atkSpeed:0.85, range:0.35, crit:0.1, knockback:0.8, special:{type:'lifesteal', amt:0.08},
    finisher:{type:'heal', name:'Ember Surge', healFrac:0.12, spdDur:4},
    color:0xff7a4a, emissive:0x8a2a11, geomScale:{x:0.55,y:1.15,z:0.55},
    desc:"A slender blade that drinks the Bloom's essence with every cut." },
  { id:'warblade', name:'Regal Warblade', icon:'⚔️', rarity:3, type:'greatsword',
    dmg:17, atkSpeed:1.32, range:0.55, crit:0, knockback:2.0, special:null,
    finisher:{type:'shockwave', name:'Ground Slam', mult:0.8},
    color:0x5aa0ff, emissive:0x1a4a8a, geomScale:{x:1.7,y:1.5,z:1.35},
    desc:'A monstrous two-handed blade — every hit sends the Bloom flying.' },
  { id:'sporecleaver', name:'Golden Sporecleaver', icon:'✨', rarity:4, type:'legendary',
    dmg:30, atkSpeed:1.08, range:0.6, crit:0.16, knockback:1.3, special:{type:'lifesteal', amt:0.14},
    finisher:{type:'nova', name:'Golden Nova', count:8, mult:0.5},
    color:0xd8a6ff, emissive:0xb4860a, geomScale:{x:1.45,y:1.4,z:1.25},
    desc:"Forged from the Elder Myconid's own crown. Legends made steel." },
  { id:'ravenousmaw', name:'The Ravenous Maw', icon:'🦴', rarity:4, type:'legendary',
    dmg:34, atkSpeed:1.4, range:0.5, crit:0.06, knockback:1.6, special:{type:'lifesteal', amt:0.18},
    finisher:{type:'devour', name:'Devour', mult:0.7, killHealFrac:0.35},
    color:0xc8e066, emissive:0x3a5a10, geomScale:{x:1.6,y:1.35,z:1.5},
    desc:"Carved from Rotmaw's own fang. Heavy, hungry, never satisfied." },
];
export const WEAPONS_BY_ID = Object.fromEntries(WEAPONS.map(w=>[w.id, w]));
